from typing import Final

ASSIGNMENT_STATUS_CANDIDATE_FOUND: Final = "candidate_found"
ASSIGNMENT_STATUS_NO_DRIVER: Final = "no_driver"

DRIVER_ENTITY_TYPE: Final = "driver"
OPTIMIZED_ROUTE_STATUS: Final = "optimized"
PICKUP_POINT_ENTITY_TYPE: Final = "pickup_point"

REASON_SHORT_PICKUP_ETA: Final = "SHORT_PICKUP_ETA"
REASON_NEAR_PICKUP_POINT: Final = "NEAR_PICKUP_POINT"
REASON_LOW_ROUTE_RISK: Final = "LOW_ROUTE_RISK"
REASON_ENOUGH_CAPACITY: Final = "ENOUGH_CAPACITY"
REASON_HIGH_ACCEPTANCE_RATE: Final = "HIGH_ACCEPTANCE_RATE"
REASON_GOOD_RAIN_MODE_SCORE: Final = "GOOD_RAIN_MODE_SCORE"
REASON_HIGH_EXPECTED_EARNING: Final = "HIGH_EXPECTED_EARNING"
REASON_GREEDY_MATCH_SELECTED: Final = "GREEDY_MATCH_SELECTED"
REASON_NO_FEASIBLE_DRIVER: Final = "NO_FEASIBLE_DRIVER"
REASON_DRIVER_UNAVAILABLE: Final = "DRIVER_UNAVAILABLE"
REASON_DRIVER_NOT_IDLE: Final = "DRIVER_NOT_IDLE"
REASON_DRIVER_DOES_NOT_ACCEPT_POOL: Final = "DRIVER_DOES_NOT_ACCEPT_POOL"
REASON_INSUFFICIENT_CAPACITY: Final = "INSUFFICIENT_CAPACITY"
REASON_PICKUP_ETA_TOO_HIGH: Final = "PICKUP_ETA_TOO_HIGH"
REASON_PICKUP_DISTANCE_TOO_FAR: Final = "PICKUP_DISTANCE_TOO_FAR"
REASON_ROUTE_RISK_TOO_HIGH: Final = "ROUTE_RISK_TOO_HIGH"

DEFAULT_MAX_DRIVER_PICKUP_ETA_MIN: Final = 15.0
DEFAULT_MAX_ALLOWED_FLOOD_RISK: Final = 0.65
DEFAULT_MAX_PICKUP_DISTANCE_KM: Final = 5.0
DEFAULT_MAX_EXTRA_CAPACITY: Final = 3
DEFAULT_TARGET_DRIVER_EARNING_VND: Final = 150_000
DEFAULT_TARGET_POOL_BONUS_VND: Final = 15_000

WEIGHT_ETA_COST: Final = 0.30
WEIGHT_DISTANCE_COST: Final = 0.20
WEIGHT_RISK_COST: Final = 0.20
WEIGHT_CAPACITY_COST: Final = 0.10
WEIGHT_ACCEPTANCE_COST: Final = 0.10
WEIGHT_RAIN_MODE_COST: Final = 0.05
WEIGHT_EARNING_COST: Final = 0.05

DEFAULT_CREATED_AT_ISO: Final = "2026-06-27T17:19:00+07:00"
